library my_prj.globals;

int promoIndex;
String namePromo = '';
String userName;
int user_id;
int promoid;
String role;
String isExist;
int statuscode = 0;
String token;
String ajoutadmin;
String category;
String idQr;
String formGenre;
String formAdd;
String user_idmod;
String rolemod;
String formNom;
String formEmail;
String formTel;
String formVille;
String expiration_date;
String description;
